version: latest

services:

  mysql-development:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_mgmt

    ports:
      - "3308:3306"


#          docker run -it \
#          -e MYSQL_ROOT_PASSWORD="root" \
#          -e MYSQL_DATABASE="users" \
#          -v $(pwd)/users_mysql_data:/var/lib/mysql \
#          -p 3306:3306 \
#          mysql:8